### ISSUE TITLE
phploc/phploc 2.1.1 requires php >=5.4

### ISSUE THREAD

**Issue by ronanguilloux** [ronanguilloux/IsoCodes#19]
PHP 5.3 is obsolete, EOL since Aug 2014

**Comment by Soullivaneuh** [comment]
Stop me if I'm wrong, but according to [semver](http://semver.org/), changed dependencies should be tagged as a new minor version (e.g. 1.2) and not a patch.

**Comment by ronanguilloux** [comment]
Didn't found this statement while reading [semver docs](http://semver.org/) : could you give us a reference or elaborate please?

**Comment by Soullivaneuh** [comment]
I'm basing on Symfony rules that are basing on semver.

For us, this need also a major version because developers working on php 5.3 need to not have BC breaks with minor or patch update of your app.

But anyway, this just concern test library and change was made only on travis. No change on composer.json so I think it could be ok. :+1:
