### ISSUE TITLE
+1 US phone number

### ISSUE THREAD

**Issue by ronanguilloux** [ronanguilloux/IsoCodes#42]
`/^(\+\d)*\s*(\(\d{3}\)\s*)*\d{3}(-{0,1}|\s{0,1})\d{2}(-{0,1}|\s{0,1})\d{2}$/`

**Comment by Soullivaneuh** [comment]
:+1: 

Why not just phone number validation with country code?

**Comment by barryvdh** [comment]
For phonenumbers, you could just require this in composer: https://github.com/giggsey/libphonenumber-for-php and create a simple wrapper around it.

	<?php
	namespace IsoCodes;
	class PhoneNumber {
		public static function validate($number, $country)
		{
			$phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
			$swissNumberProto = $phoneUtil->parse($swissNumberStr, $country);
			return $phoneUtil->isValidNumber($swissNumberProto);
		}
	}

Or just leave it in the 'suggest' function and thrown an Exception when it isn't required and you still try to use the PhoneNumber class.

**Comment by Soullivaneuh** [comment]
@ronanguilloux What do you think about our suggestions? What do you want to do?

**Comment by stof** [comment]
@ronanguilloux why not keeping it as a suggested dependency (and a dev requirement for tests) so that only people using this validator would need to get this library ?

Btw, your library is GPL 3 while the dependency is Apache-2, and these licenses are incompatible, making it impossible to use your new version of the package in a legal way,  as far as I know (note that I'm not a lawyer so I may be wrong about this)

**Comment by ronanguilloux** [comment]
@stof thanks for your suggestion, will keep in mind!

Hopefully the Apache2->Gplv3 is just one-way incompatible: 

> Apache2 software can (...) be included in GPLv3 projects, because the GPLv3 license accepts our software into GPLv3 works. However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law.
Source: https://www.apache.org/licenses/GPL-compatibility.html
